name: build and run docker on EB
on:
  push:
    branches:
      - "main"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t stevealbers/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true stevealbers/react-test npm test

      - name: "Generate deployement package"
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB 
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
          existing_bucket_name: elasticbeanstalk-us-east-1-990216757230

      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest